#!/bin/sh

FORMAT="%U,%S,%e,%P"

upper=${1:-1500}
init_sleep=${2:-0}
sleep=${2:-0}
trap "pkill -P $$; exit" SIGINT EXIT

# Keep server's stdin open so that it doesn't immediately terminate. Give the
# server a few seconds to start.
echo -n "Starting the server..."
sleep infinity | ./server > /dev/null &
sleep 2
echo " Done"

# Warm up
echo -n "Warming up the server..."
./stress 1000 2>&1 > /dev/null
echo " Done"

# Stress test runs
echo "Starting stress test"

echo "n,user,system,real,cpu"
for run in $(seq 1 1 5); do
	echo "Run $run"
	for n in $(seq 100 100 "$upper"); do
	    echo -n "$n,"
	    time -f "$FORMAT" ./stress "$n" "$init_sleep" "$sleep" 2>&1 > /dev/null
	done
done
