#!/bin/bash

if [[ $# -lt 1 ]]; then
    echo "Usage: $0 <id> [<init-sleep> [<sleep>]]"
    exit
fi

init_sleep=${2:-0}
sleep=${3:-0}

trap "pkill -P $$" EXIT

exec 3>/dev/tcp/localhost/8667
sleep "$init_sleep"

# Echo whatever we receive
while IFS= read -r line; do
    echo "recv: user$1: $line"
done <&3 &
pid=$!

echo "user$1: Join #stress"
cat >&3 <<EOF
NICK user$1
USER user$1 0 * user$1
JOIN #stress
EOF
sleep "$sleep"

echo "user$1: Write 1"
cat >&3 <<EOF
PRIVMSG #stress :Hi from user$1, how are you?
EOF
sleep "$sleep"

echo "user$1: Write 2"
cat >&3 <<EOF
PRIVMSG #stress :user$1 says they're good, thanks!
EOF
sleep "$sleep"

echo "user$1: Write 3"
cat >&3 <<EOF
PRIVMSG #stress :See you later, user$1!
EOF
sleep "$sleep"

echo "user$1: Quit"
cat >&3 <<EOF
QUIT :Bye from user$1!
EOF

# Wait until we're done receiving, otherwise terminating the script would close
# the connection prematurely
wait "$pid"
echo "user$1: Exit"
