#!/bin/bash

FORMAT="%U,%S,%e,%P"

upper=${1:-1500}
init_sleep=${2:-0}
sleep=${2:-0}
trap "pkill -P $$; exit" SIGINT EXIT

# Keep server's stdin open so that it doesn't immediately terminate. Give the
# server a few seconds to start.
echo -n "Starting the server..."
sleep infinity | ./server > /dev/null &
sleep 2
echo " done"

# Warm up
echo -n "Warming up the server..."
./stress "$upper" 2>&1 > /dev/null
echo " done"

# Stress test runs
echo "Starting stress test"

for run in $(seq 1 1 5); do
    echo "Run $run"
    echo "n,user,system,real,cpu"
    for n in $(seq 100 100 "$upper"); do
        echo -n "$n,"
        \time -f "$FORMAT" ./stress "$n" "$init_sleep" "$sleep" 2>&1 > /dev/null
    done
done
