#!/bin/bash

if [[ $# -lt 1 ]]; then
    echo "Usage: $0 <n> [<init-sleep> [<sleep>]]"
    exit
fi

init_sleep="${2:-0}"
sleep="${3:-0}"

ulimit -n $(ulimit -Hn)

echo "Starting $1 clients"
echo "$(seq $1)" | parallel --will-cite --line-buffer -j "$1" \
                            ./stress-client {} "$init_sleep" "$sleep"
